version: '3'

services:
  backend:
    build: .
    container_name: proyecto_base_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/code  # Esto monta la carpeta backend entera en /code en el contenedor
    ports:
      - "8000:8000"
    env_file: 
      - .env
    environment:
      - DEBUG=1

