services:
  backend:
    build: .
    container_name: proyecto_base_backend
    command: >
      sh -c "
        python manage.py runserver 0.0.0.0:8000
        "
    volumes:
      - ../:/code
    ports:
      - "8001:8000"
    env_file:
      - .env
    networks:
      - proyecto_base_net
    restart: always
networks:
  proyecto_base_net: